//
//  SwiftGitXError.swift
//  SwiftGitX
//
//  Created by İbrahim Çetin on 23.11.2025.
//

import libgit2

/// An error that occurs during Git operations.
///
/// `SwiftGitXError` provides detailed information about errors encountered
/// while performing Git operations. Each error includes:
/// - A ``code`` indicating what went wrong
/// - A ``category`` identifying where the error originated
/// - A human-readable ``message`` describing the error
public struct SwiftGitXError: Error {
    /// The error code indicating what went wrong.
    public let code: Code

    /// The error category identifying where the error originated.
    public let category: Category

    /// A human-readable description of the error.
    public let message: String

    private init(status: Int32) {
        self.code = Code(rawValue: Int(status)) ?? .error

        if status < 0, let error = git_error_last() {
            self.category = Category(rawValue: Int(error.pointee.klass)) ?? .none
            self.message = String(cString: error.pointee.message)
        } else {
            self.category = .none
            self.message = "no error"
        }
    }
}

// MARK: - Error Checking Helper

extension SwiftGitXError {
    /// Throws SwiftGitXError if status indicates an error.
    ///
    /// - Parameter status: The status code returned by a libgit2 operation.
    /// - Throws: `SwiftGitXError` if the status code indicates an error (negative value).
    ///
    /// ## Example
    ///
    /// ```swift
    /// let status = git_commit_create_from_stage(&oid, pointer, message, &options)
    /// try SwiftGitXError.check(status)
    /// ```
    @inline(__always)
    public static func check(_ status: Int32) throws {
        guard status >= 0 else {
            throw SwiftGitXError(status: status)
        }
    }
}

extension SwiftGitXError {
    /// Error codes returned by Git operations.
    ///
    /// Each case represents a specific error condition that can occur during
    /// Git operations. A return value of ``ok`` (0) indicates successful completion,
    /// while negative values indicate various error conditions.
    ///
    /// This enum directly reflects libgit2's `git_error_code` enumeration.
    /// The raw values correspond to the integer error codes returned directly
    /// by libgit2's operation functions.
    ///
    /// - Note: This is distinct from ``Category``, which provides additional context about
    /// where the error originated (e.g., network, filesystem, repository).
    public enum Code: Int {
        /// No error occurred; the call was successful.
        case ok = 0

        /// An error occurred; call git_error_last for more information.
        case error = -1

        /// Requested object could not be found.
        case notFound = -3

        /// Object exists preventing operation.
        case exists = -4

        /// More than one object matches.
        case ambiguous = -5

        /// Output buffer too short to hold data.
        case bufs = -6

        /// GIT_EUSER is a special error that is never generated by libgit2 code.
        /// You can return it from a callback (e.g to stop an iteration) to know that
        /// it was generated by the callback and not by libgit2.
        case user = -7

        /// Operation not allowed on bare repository.
        case bareRepo = -8

        /// HEAD refers to branch with no commits.
        case unbornBranch = -9

        /// Merge in progress prevented operation.
        case unmerged = -10

        /// Reference was not fast-forwardable.
        case nonFastForward = -11

        /// Name/ref spec was not in a valid format.
        case invalidSpec = -12

        /// Checkout conflicts prevented operation.
        case conflict = -13

        /// Lock file prevented operation.
        case locked = -14

        /// Reference value does not match expected.
        case modified = -15

        /// Authentication error.
        case auth = -16

        /// Server certificate is invalid.
        case certificate = -17

        /// Patch/merge has already been applied.
        case applied = -18

        /// The requested peel operation is not possible.
        case peel = -19

        /// Unexpected EOF.
        case eof = -20

        /// Invalid operation or input.
        case invalid = -21

        /// Uncommitted changes in index prevented operation.
        case uncommitted = -22

        /// The operation is not valid for a directory.
        case directory = -23

        /// A merge conflict exists and cannot continue.
        case mergeConflict = -24

        /// A user-configured callback refused to act.
        case passthrough = -30

        /// Signals end of iteration with iterator.
        case iterOver = -31

        /// Internal only.
        case retry = -32

        /// Hashsum mismatch in object.
        case mismatch = -33

        /// Unsaved changes in the index would be overwritten.
        case indexDirty = -34

        /// Patch application failed.
        case applyFail = -35

        /// The object is not owned by the current user.
        case owner = -36

        /// The operation timed out.
        case timeout = -37

        /// There were no changes.
        case unchanged = -38

        /// An option is not supported.
        case notSupported = -39

        /// The subject is read-only.
        case readOnly = -40
    }

    /// Error categories that identify where an error originated.
    ///
    /// Each category identifies the subsystem or component where the error occurred.
    /// Unlike ``Code``, which indicates what went wrong, categories help classify
    /// errors by their source (e.g., network, filesystem, repository, SSL).
    ///
    /// This enum directly reflects libgit2's `git_error_t` enumeration.
    /// Error categories are obtained by calling `git_error_last` to get additional
    /// context about the error beyond the error code returned by the operation.
    public enum Category: Int {
        /// No error.
        case none = 0

        /// Out of memory.
        case noMemory = 1

        /// Operating system error.
        case os = 2

        /// Invalid input.
        case invalid = 3

        /// Reference error.
        case reference = 4

        /// Zlib compression/decompression error.
        case zlib = 5

        /// Repository error.
        case repository = 6

        /// Configuration error.
        case config = 7

        /// Regular expression error.
        case regex = 8

        /// Object database error.
        case odb = 9

        /// Index error.
        case index = 10

        /// Object error.
        case object = 11

        /// Network error.
        case net = 12

        /// Tag error.
        case tag = 13

        /// Tree error.
        case tree = 14

        /// Indexer error.
        case indexer = 15

        /// SSL error.
        case ssl = 16

        /// Submodule error.
        case submodule = 17

        /// Threading error.
        case thread = 18

        /// Stash error.
        case stash = 19

        /// Checkout error.
        case checkout = 20

        /// FETCH_HEAD error.
        case fetchHead = 21

        /// Merge error.
        case merge = 22

        /// SSH error.
        case ssh = 23

        /// Filter error.
        case filter = 24

        /// Revert error.
        case revert = 25

        /// Callback error.
        case callback = 26

        /// Cherry-pick error.
        case cherryPick = 27

        /// Describe error.
        case describe = 28

        /// Rebase error.
        case rebase = 29

        /// Filesystem error.
        case filesystem = 30

        /// Patch error.
        case patch = 31

        /// Worktree error.
        case worktree = 32

        /// SHA-1 computation error.
        case sha = 33

        /// HTTP error.
        case http = 34

        /// Internal libgit2 error.
        case `internal` = 35

        /// Grafts error.
        case grafts = 36
    }
}

// MARK: - Code Convenience Properties

extension SwiftGitXError.Code {
    /// Returns true if the error indicates object/reference not found.
    public var isNotFound: Bool { self == .notFound }

    /// Returns true if the error indicates a conflict condition.
    public var isConflict: Bool { self == .conflict || self == .mergeConflict }

    /// Returns true if the error is authentication-related.
    public var isAuth: Bool { self == .auth || self == .certificate }

    /// Returns true if a resource is locked.
    public var isLocked: Bool { self == .locked }

    /// Returns true if the operation requires force flag.
    public var requiresForce: Bool { self == .nonFastForward }

    /// Returns true if there are uncommitted changes.
    public var hasUncommittedChanges: Bool { self == .uncommitted || self == .modified }
}
